api_key: x8v0ksnv2dbt2x2ca5tz42adgc4pchrc
cookie:
  expiry_days: 30
  key: prueba
  name: auth
credentials:
  usernames:
    valemilanesio:
      email: valemilanesio@gmail.com
      failed_login_attempts: 0
      first_name: Valentin
      last_name: Milanesio
      logged_in: false
      password: $2b$12$wUzfQTZu6fOV6Ppr0517bOfwyhul5dbghKuI7kNltqFWTBsatWJ..
