api_key: x8v0ksnv2dbt2x2ca5tz42adgc4pchrc
cookie:
  expiry_days: 30
  key: prueba
  name: auth
credentials:
  usernames:
    bestiacalchin:
      email: vale1016_milanesio@hotmail.com
      first_name: Julian
      last_name: Alvarez
      logged_in: false
      password: $2b$12$eDE7ZOaU0Mjul02QAGcBGO1McBEBTer.P7WTxZzWs9STgbvkBCOWm
      roles: null
    valemilanesio:
      email: valemilanesio@gmail.com
      first_name: Valentin
      last_name: Milanesio
      logged_in: false
      password: $2b$12$UneTLTHnQ.iyU.6rSbExgeCVkgg3rQ7gvNgmfd7Lm/qwqWL0GsZDm
      roles: null
