services:
  streamlit:
    build: .
    image: streamlit_reconectador:latest
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./images:/app/images
      - ./config.yaml:/app/config.yaml
